CREATE TABLE `players`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));

SELECT * FROM PLAYERS.PLAYERS;

DELETE FROM PLAYERS.PLAYERS;